import { StrictMode, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import { readAudit, readCapitalOverview, readDCAAllocation, readDCAStrategy, readOKXAssets, readOKXReconciliation, readEvents, readOverview, readPaperOrdersFiltered, readReports, readRuntimeHealth, readMarketPlanner, readScorecard, readThesisCapital, requestHalt, type AuditEvent, type CapitalOverview, type DCAAllocation, type DCAStrategy, type OKXAssets, type OKXReconciliation, type MarketPlanner, type Event, type Overview, type PaperOrder, type ReportCatalog, type RuntimeHealth, type Scorecard, type ThesisCapital } from './api'

const nav = ['Điều hành', 'Vốn', 'Bằng chứng giả lập', 'Vận hành', 'Sự cố', 'Quản trị']
type ReadModel = { overview: Overview | null; scorecard: Scorecard | null; orders: PaperOrder[]; events: Event[]; audit: AuditEvent[]; reports: ReportCatalog | null; planner: MarketPlanner | null; health: RuntimeHealth | null; capital: CapitalOverview | null; allocation: DCAAllocation | null; dca: DCAStrategy | null; assets: OKXAssets | null; reconciliation: OKXReconciliation | null; theses: ThesisCapital[] }
const initial: ReadModel = { overview: null, scorecard: null, orders: [], events: [], audit: [], reports: null, planner: null, health: null, capital: null, allocation: null, dca: null, assets: null, reconciliation: null, theses: [] }
const money = (value?: number) => new Intl.NumberFormat('vi-VN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value ?? 0)
const healthTone = (state?: string) => state === 'fresh' ? 'good' : state === 'stale' ? 'warn' : 'muted'

function App() {
  const [model, setModel] = useState<ReadModel>(initial)
  const [error, setError] = useState(false)
  const [haltOpen, setHaltOpen] = useState(false)
  const [haltReason, setHaltReason] = useState('')
  const [haltReasonCode, setHaltReasonCode] = useState('runtime_integrity')
  const [haltState, setHaltState] = useState<'idle' | 'sending' | 'sent' | 'failed'>('idle')
  const [simulation, setSimulation] = useState<Record<string, number>>({})
  const [paperStatus, setPaperStatus] = useState('')
  useEffect(() => {
    const controller = new AbortController()
    Promise.all([readOverview(controller.signal), readScorecard(controller.signal), readPaperOrdersFiltered(paperStatus, controller.signal), readEvents(controller.signal), readRuntimeHealth(controller.signal), readCapitalOverview(controller.signal), readDCAAllocation(controller.signal), readDCAStrategy(controller.signal), readOKXAssets(controller.signal), readOKXReconciliation(controller.signal), readThesisCapital(controller.signal), readAudit(controller.signal), readMarketPlanner(controller.signal), readReports(controller.signal)])
      .then(([overview, scorecard, orders, events, health, capital, allocation, dca, assets, reconciliation, theses, audit, planner, reports]) => setModel({ overview: overview.data, scorecard: scorecard.data, orders: orders.data.orders, events: events.data.events, audit: audit.data.events, reports: reports.data, planner: planner.data, health: health.data, capital: capital.data, allocation: allocation.data, dca: dca.data, assets: assets.data, reconciliation: reconciliation.data, theses: theses.data.items }))
      .catch(() => setError(true))
    return () => controller.abort()
  }, [paperStatus])
  const { overview, scorecard, orders, events, audit, reports, planner, health, capital, allocation, dca, assets, reconciliation, theses } = model
  const paper = overview?.paper
  const market = overview?.market
  const halted = overview?.halted ?? true
  const simulatedTotal = useMemo(() => Object.values(simulation).reduce((sum, value) => sum + value, 0), [simulation])
  const remainingSimulation = Math.max(0, (capital?.available_usdt ?? 0) - simulatedTotal)
  const strategicSymbols = new Set(['ETH', 'LINK', 'VIRTUAL', 'USDT'])
  const allValuedAssets = assets?.tai_san.filter(asset => asset.trang_thai_dinh_gia === 'dinh_gia' && Number(asset.gia_tri_usdt) > 0) ?? []
  const valuedAssets = allValuedAssets.filter(asset => strategicSymbols.has(asset.ma_tai_san) || Number(asset.gia_tri_usdt) >= 1)
  const hiddenDustAssets = allValuedAssets.filter(asset => !valuedAssets.includes(asset))
  const unvaluedAssets = assets?.tai_san.filter(asset => asset.trang_thai_dinh_gia !== 'dinh_gia') ?? []
  const hiddenAssets = [...hiddenDustAssets, ...unvaluedAssets]
  const totalPortfolioUSDT = valuedAssets.reduce((sum, asset) => sum + Number(asset.gia_tri_usdt), 0)
  const usdtAsset = valuedAssets.find(asset => asset.ma_tai_san === 'USDT')
  const otherValueUSDT = Math.max(0, totalPortfolioUSDT - Number(usdtAsset?.gia_tri_usdt ?? 0))
  const pct = (value: string | undefined) => totalPortfolioUSDT > 0 ? `${(Number(value ?? 0) / totalPortfolioUSDT * 100).toFixed(1)}%` : '—'
  const setAllocation = (thesisID: string, raw: number) => { const other = Object.entries(simulation).filter(([key]) => key !== thesisID).reduce((sum, [, value]) => sum + value, 0); const permitted = Math.max(0, (capital?.available_usdt ?? 0) - other); setSimulation({ ...simulation, [thesisID]: Math.min(permitted, Math.max(0, raw)) }) }
  const sendHalt = async () => { if (haltReason.trim().length < 8) return; setHaltState('sending'); try { await requestHalt(haltReasonCode, haltReason.trim()); setHaltState('sent') } catch { setHaltState('failed') } }
  return <main className="app-shell">
    <a className="skip-link" href="#content">Bỏ qua điều hướng</a>
    <aside className="sidebar"><div className="brand"><div className="brand-mark">◌</div><div><strong>BTC Agent</strong><small>Bảng điều hành</small></div></div><nav>{nav.map((item, i) => <a key={item} className={i === 0 ? 'nav active' : 'nav'} href={`#${item.replaceAll(' ', '-')}`}>{item}</a>)}</nav><section className="evidence-mini"><p className="eyebrow">Cửa sổ bằng chứng</p><strong>{paper?.total_orders ?? 0} <span>trên 30 lệnh</span></strong><div className="progress"><i style={{ width: `${Math.min(100, ((paper?.total_orders ?? 0) / 30) * 100)}%` }} /></div><p>Chỉ tích lũy bằng chứng vòng đời giả lập tự nhiên.</p></section><div className="profile"><span>OP</span><div><strong>Vận hành viên</strong><small>Được bảo vệ bởi Access</small></div></div></aside>
    <section className="workspace" id="content"><header className="safety-bar"><div><b className="badge critical">● {halted ? 'HALTED' : 'CHƯA CÓ TRẠNG THÁI DỪNG'}</b><b className="badge paper">● PAPER</b><b className="badge">GIAO DỊCH THẬT ĐÃ TẮT</b></div><div className="fresh"><i className={healthTone(health?.freshness.state)} />{error ? 'API runtime không khả dụng — chế độ an toàn' : health ? `Observer ${health.freshness.state} · ${health.freshness.age_seconds} giây` : 'Đang tải dữ liệu chỉ đọc…'} · API v1</div></header>
      <div className="page-header"><div><p className="eyebrow">Thông tin vận hành</p><h1>Vận hành, vốn, bằng chứng.</h1><p>Góc nhìn chính xác về ranh giới an toàn và phân bổ USDT.</p></div><button id="request-halt" onClick={() => setHaltOpen(true)} aria-label="Yêu cầu vận hành viên dừng khẩn">Yêu cầu dừng khẩn&nbsp; ↯</button></div>
      {haltOpen && <section className="halt-dialog" role="dialog" aria-modal="true" aria-labelledby="halt-title"><div className="halt-dialog__body"><p className="eyebrow">Kiểm soát an toàn một chiều</p><h2 id="halt-title">Yêu cầu vận hành viên dừng khẩn</h2><p>Thao tác này không khôi phục giao dịch. Danh tính đã xác thực, lý do và biên nhận idempotency được lưu audit.</p>{haltState === 'sent' ? <p className="halt-result success">Đã ghi nhận yêu cầu dừng. Có thể tải lại trạng thái an toàn.</p> : <><label htmlFor="halt-code">Mã lý do</label><select id="halt-code" value={haltReasonCode} onChange={event => setHaltReasonCode(event.target.value)}><option value="runtime_integrity">Toàn vẹn runtime</option><option value="exchange_state">Trạng thái sàn</option><option value="capital_integrity">Toàn vẹn vốn</option><option value="security_incident">Sự cố bảo mật</option></select><label htmlFor="halt-reason">Tóm tắt <span>8–500 ký tự</span></label><textarea id="halt-reason" value={haltReason} onChange={e => setHaltReason(e.target.value)} maxLength={500} placeholder="Mô tả điều kiện không an toàn đã quan sát." autoFocus />{haltState === 'failed' && <p className="halt-result error">Yêu cầu bị từ chối. Xác nhận đăng nhập Access và thử lại với lý do rõ ràng.</p>}<div className="halt-actions"><button className="secondary" onClick={() => setHaltOpen(false)}>Hủy</button><button className="danger" disabled={haltState === 'sending' || haltReason.trim().length < 8} onClick={sendHalt}>{haltState === 'sending' ? 'Đang ghi nhận…' : 'Ghi nhận yêu cầu dừng'}</button></div></>}</div></section>}
      <section className="hero-grid"><article className="card"><div className="card-head"><div><p className="eyebrow">Toàn vẹn runtime</p><h2>{health?.freshness.state === 'fresh' ? 'Bằng chứng observer đang mới.' : 'Bằng chứng observer chưa khả dụng.'}</h2></div><em className={`orb ${healthTone(health?.freshness.state)}`} /></div><div className="checks"><div><i className={healthTone(health?.freshness.state)} /> <span><strong>{health?.heartbeat.state ?? 'Chờ ảnh chụp'}</strong><small>Nhịp sống · {health?.heartbeat.age_seconds ?? '—'} giây</small></span><b>{health?.freshness.state === 'fresh' ? '✓' : '—'}</b></div><div><i className={health?.scheduler.count === 1 ? 'good' : 'warn'} /> <span><strong>{health?.scheduler.count === 1 ? '1 tiến trình hoạt động' : 'Chưa xác minh'}</strong><small>Scheduler đơn thể · artifact observer</small></span><b>{health?.scheduler.count === 1 ? '✓' : '—'}</b></div><div><i className={health?.lease.fresh ? 'good' : 'warn'} /> <span><strong>{health?.lease.instance_id ?? 'Chưa có bằng chứng lease'}</strong><small>Lease · DB {health?.database_state ?? 'không khả dụng'}</small></span><b>{health?.lease.fresh ? '✓' : '—'}</b></div></div></article><article className="card authority"><div className="card-head"><div><p className="eyebrow">Quyền thị trường</p><h2>Chỉ quan sát. Không triển khai.</h2></div><b className="watch">{market?.permission ?? 'WATCH'}</b></div><div className="authority-core"><div className="ring"><strong>0.00<small>USDT</small></strong></div><div><small>Được thực thi lúc này</small><strong>{market?.regime ?? 'CHƯA RÕ THỊ TRƯỜNG'}</strong><p>Quyền {market?.permission ?? 'WATCH'} · {market?.accumulation_phase ?? 'Chờ phân tích'}</p></div></div><div className="gates"><span>Cổng rủi ro <b>ĐẠT</b></span><span>Cổng thực thi <b>BỊ CHẶN</b></span><span>Vận hành viên halt <b>ACTIVE</b></span></div></article></section>
      <section className="planner-panel" id="Planner"><div className="section-title"><div><p className="eyebrow">Giải thích thị trường và kế hoạch</p><h2>{planner?.available ? `${planner.regime} · ${planner.permission}` : 'Chưa có quyết định thị trường có kiểu dữ liệu.'}</h2><p>{planner?.permission_reason ?? 'Chờ phân tích thị trường đã lưu; không suy luận từ dữ liệu thiếu.'}</p></div><b className="status-pill warn">{planner?.plan_state ?? 'UNAVAILABLE'}</b></div>{planner?.available ? <div className="planner-grid"><div><small>Giá BTC tham chiếu</small><strong>{money(planner.price_usdt)} USDT</strong><p>{planner.market_summary}</p></div><div><small>Các cổng rủi ro</small><strong>Rủi ro {planner.risk_level}</strong><p>Rơi dao: {planner.falling_knife_risk} · FOMO: {planner.fomo_risk}</p></div><div><small>Trạng thái kế hoạch</small><strong>{planner.plan_state}</strong><p>{planner.plan_summary}</p></div></div> : null}{planner?.warnings.length ? <div className="capital-issues"><b>Cảnh báo kế hoạch</b>{planner.warnings.map(item => <span key={item}>{item}</span>)}</div> : null}</section>
      <section className="allocation-panel" id="Von-DCA"><div className="section-title"><div><p className="eyebrow">Vốn DCA</p><h2>Allocation epoch — vốn được cấp có kiểm soát</h2><p>80% USDT khả dụng có thể trở thành envelope DCA; 20% còn lại là đệm. Epoch không tự tạo quyền BUY.</p></div><b className="status-pill">{allocation?.trang_thai === 'da_cap_von' ? 'Đã cấp vốn' : 'Chưa cấp vốn'}</b></div><div className="allocation-metrics"><div><small>USDT đã xác minh</small><strong>{money(allocation?.usdt_kha_dung ?? 0)}</strong></div><div><small>DCA envelope</small><strong>{money(allocation?.dca_envelope_usdt ?? 0)}</strong></div><div><small>Đệm</small><strong>{allocation?.ty_le_dem_phan_tram ?? 20}%</strong></div><div><small>Global cap hiện tại</small><strong>{allocation?.global_cap_phan_tram ?? 20}%</strong></div></div>{allocation?.ly_do_auto_halt ? <p className="allocation-halt">Auto-halt BUY: {allocation.ly_do_auto_halt}</p> : null}{allocation?.phan_bo.length ? <div className="allocation-items">{allocation.phan_bo.map(item=><div key={item.thesis_id}><b>{item.symbol.replace('USDT','')}</b><span>{item.ty_le_phan_tram}% trần</span><strong>{money(item.amount_usdt)} USDT</strong></div>)}</div> : <p className="allocation-empty">Chưa có epoch. Bot vẫn halted; không có vốn thesis hay quyền BUY.</p>}<ul className="allocation-warnings">{allocation?.canh_bao.map(item=><li key={item}>{item}</li>)}</ul></section>
      <section className="dca-strategy" id="Chien-luoc-DCA"><div className="section-title"><div><p className="eyebrow">Chiến lược DCA</p><h2>Danh sách DCA được chỉ định: ETH, LINK và VIRTUAL.</h2><p>Đây là universe DCA của bot, không phải quyền execution. Chỉ USDT được cấp trong thesis riêng mới có thể trở thành vốn DCA.</p></div><b className="status-pill warn">{dca?.giai_doan ?? 'HALTED_SHADOW'}</b></div><div className="dca-rules"><div><small>Cơ chế</small><strong>{dca?.co_che ?? 'Limit/post-only · Ba lớp 25% / 35% / 40%'}</strong></div><div><small>Quyền thực thi</small><strong>{dca?.co_quyen_thuc_thi ? 'Được cấp' : 'Bị chặn'}</strong></div><div><small>Vốn DCA được cấp</small><strong>{money((dca?.ung_vien ?? []).reduce((sum, item) => sum + Number(item.von_duoc_cap_usdt), 0))} USDT</strong></div></div><div className="dca-layers">{dca?.cac_lop.map(layer => <div key={layer.ten}><b>{layer.ten}</b><strong>{layer.ty_le_phan_tram}%</strong><small>{layer.quy_tac}</small></div>)}</div><div className="dca-candidates">{dca?.ung_vien.map(item => <article key={item.ma_tai_san}><header><strong>{item.ma_tai_san}</strong><span className={`risk ${item.muc_rui_ro}`}>Rủi ro {item.muc_rui_ro.replaceAll('_', ' ')}</span></header><p>{item.luan_diem}</p><div><small>Trạng thái</small><b>{item.trang_thai === 'danh_sach_dca' ? 'Thuộc danh sách DCA' : item.trang_thai}</b></div><div><small>Thesis / vốn được cấp</small><b>{item.thesis_id || 'Chưa có thesis'} · {item.von_duoc_cap_usdt} USDT</b></div><ul>{item.blocker.map(blocker => <li key={blocker}>{blocker}</li>)}</ul></article>)}</div></section>
      <section className="okx-assets" id="Tai-san-OKX">
        <div className="section-title"><div><p className="eyebrow">Danh mục Spot tại OKX</p><h2>{assets?.trang_thai === 'da_xac_minh' ? 'Tổng quan tài khoản đã xác minh' : 'Danh mục chưa khả dụng'}</h2><p>Số dư tại sàn chỉ dùng để quan sát và đối soát. Không phải vốn DCA, không tạo thesis, không cấp quyền mua hoặc bán.</p></div><b className={`status-pill ${assets?.trang_thai === 'da_xac_minh' ? 'good' : 'warn'}`}>{assets?.trang_thai ?? 'khong_kha_dung'}</b></div>
        {assets?.thoi_diem_quan_sat && <p className="asset-observed">Đồng bộ lúc {new Date(assets.thoi_diem_quan_sat).toLocaleString('vi-VN')} · Giá Spot công khai OKX · {valuedAssets.length} tài sản chính · {hiddenAssets.length} số dư nhỏ đã ẩn</p>}
        <div className="portfolio-hero"><div><small>Tổng tài sản đã định giá</small><strong>{money(totalPortfolioUSDT)} <em>USDT</em></strong><p>Không cộng các coin chưa có giá USDT đã xác minh.</p></div><div><small>USDT sẵn sàng</small><strong>{money(Number(usdtAsset?.kha_dung))} <em>USDT</em></strong><p>{pct(usdtAsset?.gia_tri_usdt)} danh mục đã định giá</p></div><div><small>Giá trị coin đang nắm</small><strong>{money(otherValueUSDT)} <em>USDT</em></strong><p>{valuedAssets.filter(asset => asset.ma_tai_san !== 'USDT').length} tài sản được định giá</p></div></div>
        {valuedAssets.length ? <div className="holdings"><div className="holdings-title"><div><p className="eyebrow">Danh mục chính</p><h3>Phân bổ theo giá trị USDT</h3></div><span>Chỉ số dư Spot · không phải phân bổ chiến lược</span></div>{valuedAssets.map(asset => <article className="holding-card" key={asset.ma_tai_san}><div className="holding-symbol"><b>{asset.ma_tai_san.slice(0, 1)}</b><div><strong>{asset.ma_tai_san}</strong><small>{asset.trang_thai_gan_thesis === 'chua_gan_thesis' ? 'Chưa gắn thesis' : 'Tài sản định giá chuẩn'}</small></div></div><div className="holding-value"><strong>{money(Number(asset.gia_tri_usdt))} USDT</strong><small>{pct(asset.gia_tri_usdt)} danh mục</small></div><div className="holding-bar"><i style={{ width: pct(asset.gia_tri_usdt) }} /></div><div className="holding-amount"><span>Đang nắm</span><strong>{asset.tong}</strong><small>Khả dụng {asset.kha_dung} · Khóa {asset.dang_khoa}</small></div></article>)}</div> : <Empty title="Chưa có danh mục được định giá" text="Chỉ hiển thị tổng vốn khi nguồn giá USDT công khai đã xác minh." />}
        {hiddenAssets.length ? <details className="dust-ledger"><summary><span>Số dư nhỏ đã ẩn khỏi danh mục chính</span><b>{hiddenAssets.length} tài sản</b></summary><p>Coin dưới 1 USDT được ẩn để danh mục dễ đọc. ETH, LINK, VIRTUAL và USDT luôn giữ. Số dư không bị bán, chuyển, xóa hoặc gán giá trị 0.</p>{hiddenAssets.map(asset => <div key={asset.ma_tai_san}><strong>{asset.ma_tai_san}</strong><span>{asset.tong}</span><small>{asset.trang_thai_dinh_gia === 'dinh_gia' ? `${money(Number(asset.gia_tri_usdt))} USDT · dưới ngưỡng 1 USDT` : 'Chưa có giá USDT đã xác minh'}</small></div>)}</details> : null}
        {assets?.canh_bao.length ? <div className="capital-issues"><b>Cảnh báo tài sản</b>{assets.canh_bao.map(item => <span key={item}>{item}</span>)}</div> : null}{reconciliation?.trang_thai === 'can_ra_soat' ? <div className="capital-issues"><b>Cần rà soát đối soát</b><span>Tài sản chưa gắn thesis: {reconciliation.tai_san_chua_gan_thesis.join(', ')}. Không suy diễn thành quyền mua, bán hoặc vốn DCA.</span></div> : null}</section>
      <section className="capital-center" id="Capital"><div className="section-title"><div><p className="eyebrow">Trạng thái vốn USDT</p><h2>Vốn được quan sát, không áp dụng tại đây.</h2><p>Góc nhìn theo thesis. Mô phỏng cục bộ không tạo reservation hoặc ghi trạng thái runtime.</p></div><b className={`status-pill ${capital?.projection_state === 'healthy' ? 'good' : 'warn'}`}>{capital?.projection_state ?? 'khong_kha_dung'}</b></div><div className="capital-metrics"><Metric label="DCA khả dụng" value={money(capital?.available_usdt)} /><Metric label="Đã giữ chỗ" value={money(capital?.reserved_usdt)} /><Metric label="Đã khớp xác nhận" value={money(capital?.filled_usdt)} /><Metric label="Hạn mức thesis" value={money(capital?.max_exposure_usdt)} /></div><div className="capital-grid"><article className="panel thesis-panel"><div className="title"><div><p className="eyebrow">Bản đồ phân bổ thesis</p><h2>Nguồn gốc bất biến</h2></div><span>USDT</span></div>{theses.length ? theses.map(thesis => <div className="thesis-row" key={thesis.thesis_id}><div><strong>{thesis.thesis_id}</strong><small>{thesis.symbol} · {thesis.status}</small></div><div className="allocation-bar"><i style={{ width: `${Math.min(100, ((thesis.filled_usdt + thesis.reserved_usdt) / Math.max(thesis.max_exposure_usdt, 1)) * 100)}%` }} /></div><div className="thesis-values"><b>{money(thesis.remaining_usdt)}</b><small>Còn lại</small></div></div>) : <Empty title="Chưa có sổ vốn thesis" text="Runtime chưa ghi nhận phân bổ thesis." />}</article><article className="panel simulation"><p className="eyebrow">Mô phỏng cục bộ</p><h2>Chỉ phân bổ cục bộ</h2><p>Đóng băng theo ảnh chụp chỉ đọc hiện tại. Không gửi request và không thể giữ chỗ hoặc giải phóng vốn.</p>{theses.map(thesis => <label key={thesis.thesis_id} htmlFor={`sim-${thesis.thesis_id}`}><span>{thesis.thesis_id}</span><input id={`sim-${thesis.thesis_id}`} type="number" min="0" max={capital?.available_usdt ?? 0} value={simulation[thesis.thesis_id] ?? ''} placeholder="0.00" onChange={e => setAllocation(thesis.thesis_id, Number(e.target.value))} /></label>)}<div className="simulation-total"><span>Phân bổ giả định</span><strong>{money(simulatedTotal)} USDT</strong><small>{money(remainingSimulation)} USDT còn lại từ vốn khả dụng đang hiển thị</small></div></article></div>{capital?.issues.length ? <div className="capital-issues"><b>Cần lưu ý khi audit vốn</b>{capital.issues.map(issue => <span key={issue}>{issue}</span>)}</div> : null}</section>
      <section className="evidence" id="Paper-evidence"><div><p className="eyebrow">Bằng chứng vòng đời giả lập</p><h2>Bằng chứng được tích lũy, không được tạo giả.</h2><p>{scorecard?.readiness ?? 'INSUFFICIENT_EVIDENCE'} · Trạng thái chưa rõ {scorecard?.unknown_statuses ?? 0}; thiếu thời điểm kết thúc {scorecard?.missing_terminal_timestamps ?? 0}.</p></div><div className="stats"><span><strong>{paper?.total_orders ?? 0}<small>/30</small></strong>Lệnh</span><span><strong>{paper?.terminal_orders ?? 0}<small>/15</small></strong>Kết thúc</span><span><strong>{scorecard?.open_orders ?? 0}</strong>Đang mở</span></div><a href="#paper-orders">Luồng bằng chứng →</a></section>
      <section className="reports-panel" id="Reports"><p className="eyebrow">Thư viện báo cáo an toàn</p><h2>{reports?.reports.length ? 'Báo cáo đã phê duyệt' : 'Không có báo cáo trong allowlist.'}</h2><p>{reports?.reports.length ? 'Mọi báo cáo có ID cố định và được duyệt trước khi hiển thị.' : 'Default-deny đang bật. Không thể duyệt hoặc tải file runtime từ console này.'}</p></section>
      <section className="audit-panel" id="Governance"><div className="title"><div><p className="eyebrow">Sổ quản trị</p><h2>Audit vận hành đã làm sạch</h2></div><span>Danh tính người xem được che</span></div>{audit.length ? audit.map(item => <div className="audit-row" key={item.id}><time>{new Date(item.timestamp).toLocaleString()}</time><strong>{item.action}</strong><span>{item.result}</span><small>{item.actor}</small></div>) : <Empty title="Không có sự kiện audit được giữ lại" text="Payload và lý do tự do không bao giờ được hiển thị." />}</section>
      <section className="lower"><article className="panel" id="paper-orders"><div className="title"><div><p className="eyebrow">Luồng lệnh giả lập</p><h2>Lệnh lưu gần nhất</h2></div><label className="paper-filter" htmlFor="paper-status">Vòng đời <select id="paper-status" value={paperStatus} onChange={event => setPaperStatus(event.target.value)}><option value="">Tất cả</option><option value="OPEN">Đang mở</option><option value="FILLED">Đã khớp</option><option value="INVALIDATED">Đã vô hiệu</option><option value="EXPIRED">Đã hết hạn</option><option value="CANCELLED">Đã hủy</option></select></label></div>{orders.length ? orders.map(order => <div className="attention" key={order.id}><i className={order.status === 'OPEN' ? 'amber' : 'green'} /><div><strong>{order.symbol} · lớp {order.layer} · {order.status}</strong><small>{new Date(order.timestamp).toLocaleString()} · {order.notional.toFixed(2)} USDT</small></div><b>›</b></div>) : <Empty title="Chưa có lệnh giả lập" text="Bằng chứng scheduler tự nhiên sẽ xuất hiện tại đây." />}</article><article className="panel" id="Incidents"><div className="title"><div><p className="eyebrow">Dòng thời gian hệ thống</p><h2>Sự kiện runtime đã làm sạch</h2></div><button aria-label="Dòng thời gian chỉ đọc">⌘</button></div><ol>{events.length ? events.map(event => <li key={event.id}><time>{new Date(event.timestamp).toLocaleTimeString()}</time><i/><div><strong>{event.source} · {event.severity}</strong><small>{event.type}</small></div></li>) : <li><time>—</time><i/><div><strong>Không có sự kiện chờ</strong><small>Payload được chủ động không hiển thị.</small></div></li>}</ol></article></section><footer>Console đọc trước · v1 <span>Không có quyền đặt lệnh, hủy lệnh, khôi phục hoặc cấu hình.</span></footer></section></main>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="capital-metric"><small>{label}</small><strong>{value}<em> USDT</em></strong></div> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><strong>{title}</strong><small>{text}</small></div> }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
