import { StrictMode, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import { readAudit, readCapitalOverview, readEvents, readOverview, readPaperOrders, readReports, readRuntimeHealth, readMarketPlanner, readScorecard, readThesisCapital, requestHalt, type AuditEvent, type CapitalOverview, type MarketPlanner, type Event, type Overview, type PaperOrder, type ReportCatalog, type RuntimeHealth, type Scorecard, type ThesisCapital } from './api'

const nav = ['Command', 'Capital', 'Paper evidence', 'Operations', 'Incidents', 'Governance']
type ReadModel = { overview: Overview | null; scorecard: Scorecard | null; orders: PaperOrder[]; events: Event[]; audit: AuditEvent[]; reports: ReportCatalog | null; planner: MarketPlanner | null; health: RuntimeHealth | null; capital: CapitalOverview | null; theses: ThesisCapital[] }
const initial: ReadModel = { overview: null, scorecard: null, orders: [], events: [], audit: [], reports: null, planner: null, health: null, capital: null, theses: [] }
const money = (value?: number) => new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value ?? 0)
const healthTone = (state?: string) => state === 'fresh' ? 'good' : state === 'stale' ? 'warn' : 'muted'

function App() {
  const [model, setModel] = useState<ReadModel>(initial)
  const [error, setError] = useState(false)
  const [haltOpen, setHaltOpen] = useState(false)
  const [haltReason, setHaltReason] = useState('')
  const [haltState, setHaltState] = useState<'idle' | 'sending' | 'sent' | 'failed'>('idle')
  const [simulation, setSimulation] = useState<Record<string, number>>({})
  useEffect(() => {
    const controller = new AbortController()
    Promise.all([readOverview(controller.signal), readScorecard(controller.signal), readPaperOrders(controller.signal), readEvents(controller.signal), readRuntimeHealth(controller.signal), readCapitalOverview(controller.signal), readThesisCapital(controller.signal), readAudit(controller.signal), readMarketPlanner(controller.signal), readReports(controller.signal)])
      .then(([overview, scorecard, orders, events, health, capital, theses, audit, planner, reports]) => setModel({ overview: overview.data, scorecard: scorecard.data, orders: orders.data.orders, events: events.data.events, audit: audit.data.events, reports: reports.data, planner: planner.data, health: health.data, capital: capital.data, theses: theses.data.items }))
      .catch(() => setError(true))
    return () => controller.abort()
  }, [])
  const { overview, scorecard, orders, events, audit, reports, planner, health, capital, theses } = model
  const paper = overview?.paper
  const market = overview?.market
  const halted = overview?.halted ?? true
  const simulatedTotal = useMemo(() => Object.values(simulation).reduce((sum, value) => sum + value, 0), [simulation])
  const remainingSimulation = Math.max(0, (capital?.available_usdt ?? 0) - simulatedTotal)
  const setAllocation = (thesisID: string, raw: number) => { const other = Object.entries(simulation).filter(([key]) => key !== thesisID).reduce((sum, [, value]) => sum + value, 0); const permitted = Math.max(0, (capital?.available_usdt ?? 0) - other); setSimulation({ ...simulation, [thesisID]: Math.min(permitted, Math.max(0, raw)) }) }
  const sendHalt = async () => { if (haltReason.trim().length < 8) return; setHaltState('sending'); try { await requestHalt(haltReason.trim()); setHaltState('sent') } catch { setHaltState('failed') } }
  return <main className="app-shell">
    <a className="skip-link" href="#content">Bỏ qua điều hướng</a>
    <aside className="sidebar"><div className="brand"><div className="brand-mark">◌</div><div><strong>BTC Agent</strong><small>Operator console</small></div></div><nav>{nav.map((item, i) => <a key={item} className={i === 0 ? 'nav active' : 'nav'} href={`#${item.replaceAll(' ', '-')}`}>{item}</a>)}</nav><section className="evidence-mini"><p className="eyebrow">Evidence window</p><strong>{paper?.total_orders ?? 0} <span>of 30 orders</span></strong><div className="progress"><i style={{ width: `${Math.min(100, ((paper?.total_orders ?? 0) / 30) * 100)}%` }} /></div><p>Natural paper lifecycle only.</p></section><div className="profile"><span>OP</span><div><strong>Operator</strong><small>Access protected</small></div></div></aside>
    <section className="workspace" id="content"><header className="safety-bar"><div><b className="badge critical">● {halted ? 'HALTED' : 'HALT STATUS UNAVAILABLE'}</b><b className="badge paper">● PAPER</b><b className="badge">REAL TRADING DISABLED</b></div><div className="fresh"><i className={healthTone(health?.freshness.state)} />{error ? 'Runtime API unavailable — safe fallback' : health ? `Observer ${health.freshness.state} · ${health.freshness.age_seconds}s` : 'Loading read model…'} · API v1</div></header>
      <div className="page-header"><div><p className="eyebrow">Operational intelligence</p><h1>Runtime, capital, evidence.</h1><p>A precise view of safety boundaries and USDT allocation posture.</p></div><button id="request-halt" onClick={() => setHaltOpen(true)} aria-label="Request an operator halt">Request halt&nbsp; ↯</button></div>
      {haltOpen && <section className="halt-dialog" role="dialog" aria-modal="true" aria-labelledby="halt-title"><div className="halt-dialog__body"><p className="eyebrow">One-way safety control</p><h2 id="halt-title">Request an operator halt</h2><p>This cannot resume trading. Your authenticated identity, reason and idempotency receipt are recorded.</p>{haltState === 'sent' ? <p className="halt-result success">Halt request recorded. Reloading state is safe.</p> : <><label htmlFor="halt-reason">Reason <span>8–500 characters</span></label><textarea id="halt-reason" value={haltReason} onChange={e => setHaltReason(e.target.value)} maxLength={500} placeholder="Describe the observed unsafe condition." autoFocus />{haltState === 'failed' && <p className="halt-result error">Request rejected. Confirm Access login and try once with a clear reason.</p>}<div className="halt-actions"><button className="secondary" onClick={() => setHaltOpen(false)}>Cancel</button><button className="danger" disabled={haltState === 'sending' || haltReason.trim().length < 8} onClick={sendHalt}>{haltState === 'sending' ? 'Recording…' : 'Record halt request'}</button></div></>}</div></section>}
      <section className="hero-grid"><article className="card"><div className="card-head"><div><p className="eyebrow">Runtime integrity</p><h2>{health?.freshness.state === 'fresh' ? 'Observer evidence is current.' : 'Observer evidence unavailable.'}</h2></div><em className={`orb ${healthTone(health?.freshness.state)}`} /></div><div className="checks"><div><i className={healthTone(health?.freshness.state)} /> <span><strong>{health?.heartbeat.state ?? 'Awaiting snapshot'}</strong><small>Heartbeat · {health?.heartbeat.age_seconds ?? '—'} seconds</small></span><b>{health?.freshness.state === 'fresh' ? '✓' : '—'}</b></div><div><i className={health?.scheduler.count === 1 ? 'good' : 'warn'} /> <span><strong>{health?.scheduler.count === 1 ? '1 active' : 'Not verified'}</strong><small>Scheduler singleton · observer artifact</small></span><b>{health?.scheduler.count === 1 ? '✓' : '—'}</b></div><div><i className={health?.lease.fresh ? 'good' : 'warn'} /> <span><strong>{health?.lease.instance_id ?? 'No lease evidence'}</strong><small>Lease · DB {health?.database_state ?? 'unavailable'}</small></span><b>{health?.lease.fresh ? '✓' : '—'}</b></div></div></article><article className="card authority"><div className="card-head"><div><p className="eyebrow">Market authority</p><h2>Observe. Do not deploy.</h2></div><b className="watch">{market?.permission ?? 'WATCH'}</b></div><div className="authority-core"><div className="ring"><strong>0.00<small>USDT</small></strong></div><div><small>Executable now</small><strong>{market?.regime ?? 'MARKET UNKNOWN'}</strong><p>Permission {market?.permission ?? 'WATCH'} · {market?.accumulation_phase ?? 'Awaiting analysis'}</p></div></div><div className="gates"><span>Risk gate <b>PASS</b></span><span>Execution gate <b>BLOCKED</b></span><span>Operator halt <b>ACTIVE</b></span></div></article></section>
      <section className="planner-panel" id="Planner"><div className="section-title"><div><p className="eyebrow">Market & planner explanation</p><h2>{planner?.available ? `${planner.regime} · ${planner.permission}` : 'No typed market decision yet.'}</h2><p>{planner?.permission_reason ?? 'Awaiting a persisted market analysis; no inference from incomplete data.'}</p></div><b className="status-pill warn">{planner?.plan_state ?? 'UNAVAILABLE'}</b></div>{planner?.available ? <div className="planner-grid"><div><small>BTC reference</small><strong>{money(planner.price_usdt)} USDT</strong><p>{planner.market_summary}</p></div><div><small>Risk gates</small><strong>{planner.risk_level} risk</strong><p>Falling knife: {planner.falling_knife_risk} · FOMO: {planner.fomo_risk}</p></div><div><small>Planner posture</small><strong>{planner.plan_state}</strong><p>{planner.plan_summary}</p></div></div> : null}{planner?.warnings.length ? <div className="capital-issues"><b>Planner warnings</b>{planner.warnings.map(item => <span key={item}>{item}</span>)}</div> : null}</section>
      <section className="capital-center" id="Capital"><div className="section-title"><div><p className="eyebrow">USDT capital posture</p><h2>Capital is observed, never applied here.</h2><p>Thesis-first view. Local what-if never creates a reservation or writes runtime state.</p></div><b className={`status-pill ${capital?.projection_state === 'healthy' ? 'good' : 'warn'}`}>{capital?.projection_state ?? 'unavailable'}</b></div><div className="capital-metrics"><Metric label="Available DCA" value={money(capital?.available_usdt)} /><Metric label="Reserved" value={money(capital?.reserved_usdt)} /><Metric label="Confirmed filled" value={money(capital?.filled_usdt)} /><Metric label="Thesis envelope" value={money(capital?.max_exposure_usdt)} /></div><div className="capital-grid"><article className="panel thesis-panel"><div className="title"><div><p className="eyebrow">Thesis allocation map</p><h2>Immutable provenance</h2></div><span>USDT</span></div>{theses.length ? theses.map(thesis => <div className="thesis-row" key={thesis.thesis_id}><div><strong>{thesis.thesis_id}</strong><small>{thesis.symbol} · {thesis.status}</small></div><div className="allocation-bar"><i style={{ width: `${Math.min(100, ((thesis.filled_usdt + thesis.reserved_usdt) / Math.max(thesis.max_exposure_usdt, 1)) * 100)}%` }} /></div><div className="thesis-values"><b>{money(thesis.remaining_usdt)}</b><small>remaining</small></div></div>) : <Empty title="No thesis capital ledger" text="The runtime has not instrumented a thesis allocation yet." />}</article><article className="panel simulation"><p className="eyebrow">What-if sandbox</p><h2>Local allocation only</h2><p>Frozen against the current read snapshot. This sends no request and cannot reserve or release capital.</p>{theses.map(thesis => <label key={thesis.thesis_id} htmlFor={`sim-${thesis.thesis_id}`}><span>{thesis.thesis_id}</span><input id={`sim-${thesis.thesis_id}`} type="number" min="0" max={capital?.available_usdt ?? 0} value={simulation[thesis.thesis_id] ?? ''} placeholder="0.00" onChange={e => setAllocation(thesis.thesis_id, Number(e.target.value))} /></label>)}<div className="simulation-total"><span>Hypothetical allocation</span><strong>{money(simulatedTotal)} USDT</strong><small>{money(remainingSimulation)} USDT remains from displayed available capital</small></div></article></div>{capital?.issues.length ? <div className="capital-issues"><b>Capital audit attention</b>{capital.issues.map(issue => <span key={issue}>{issue}</span>)}</div> : null}</section>
      <section className="evidence" id="Paper-evidence"><div><p className="eyebrow">Paper lifecycle evidence</p><h2>Evidence is earned, never manufactured.</h2><p>{scorecard?.readiness ?? 'INSUFFICIENT_EVIDENCE'} · Unknown statuses {scorecard?.unknown_statuses ?? 0}; missing terminal timestamps {scorecard?.missing_terminal_timestamps ?? 0}.</p></div><div className="stats"><span><strong>{paper?.total_orders ?? 0}<small>/30</small></strong>Orders</span><span><strong>{paper?.terminal_orders ?? 0}<small>/15</small></strong>Terminal</span><span><strong>{scorecard?.open_orders ?? 0}</strong>Open</span></div><a href="#paper-orders">Evidence feed →</a></section>
      <section className="reports-panel" id="Reports"><p className="eyebrow">Safe reports library</p><h2>{reports?.reports.length ? 'Approved reports' : 'No reports are allowlisted.'}</h2><p>{reports?.reports.length ? 'Every report is fixed-ID and reviewed before exposure.' : 'Default-deny is active. Runtime files cannot be browsed or downloaded from this console.'}</p></section>
      <section className="audit-panel" id="Governance"><div className="title"><div><p className="eyebrow">Governance ledger</p><h2>Sanitized operator audit</h2></div><span>Viewer identities masked</span></div>{audit.length ? audit.map(item => <div className="audit-row" key={item.id}><time>{new Date(item.timestamp).toLocaleString()}</time><strong>{item.action}</strong><span>{item.result}</span><small>{item.actor}</small></div>) : <Empty title="No audit events retained" text="Payloads and free-text reasons are never exposed." />}</section>
      <section className="lower"><article className="panel" id="paper-orders"><div className="title"><div><p className="eyebrow">Paper order feed</p><h2>Latest retained orders</h2></div><button aria-label="Read-only feed">↗</button></div>{orders.length ? orders.map(order => <div className="attention" key={order.id}><i className={order.status === 'OPEN' ? 'amber' : 'green'} /><div><strong>{order.symbol} · layer {order.layer} · {order.status}</strong><small>{new Date(order.timestamp).toLocaleString()} · {order.notional.toFixed(2)} USDT</small></div><b>›</b></div>) : <Empty title="No paper orders yet" text="Natural scheduler evidence will appear here." />}</article><article className="panel" id="Incidents"><div className="title"><div><p className="eyebrow">System timeline</p><h2>Sanitized runtime events</h2></div><button aria-label="Read-only timeline">⌘</button></div><ol>{events.length ? events.map(event => <li key={event.id}><time>{new Date(event.timestamp).toLocaleTimeString()}</time><i/><div><strong>{event.source} · {event.severity}</strong><small>{event.type}</small></div></li>) : <li><time>—</time><i/><div><strong>No pending events</strong><small>Payloads are intentionally not exposed.</small></div></li>}</ol></article></section><footer>Read-first console · v1 <span>No order, cancel, resume or configuration authority.</span></footer></section></main>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="capital-metric"><small>{label}</small><strong>{value}<em> USDT</em></strong></div> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><strong>{title}</strong><small>{text}</small></div> }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
