package usertext

import "strings"

var telegramVietnameseReplacer = strings.NewReplacer(
	"READ_ONLY — no order placed.", "Bot giữ nguyên trạng thái, không mở lệnh mới.",
	"HERMES INTELLIGENCE BRIEF", "BẢN PHÂN TÍCH VÀ KẾ HOẠCH CỦA HERMES",
	"EXECUTIVE DECISION", "KẾT LUẬN NHANH",
	"GLOBAL & BTC REGIME", "BỨC TRANH CHUNG VÀ TRẠNG THÁI BTC",
	"MM / FLOW / LIQUIDITY", "DÒNG TIỀN LỚN VÀ THANH KHOẢN",
	"ACCUMULATION / DISTRIBUTION MAP", "BẢN ĐỒ VÙNG GOM VÀ PHÂN PHỐI",
	"CAPITAL ALLOCATION", "KẾ HOẠCH PHÂN BỔ VỐN",
	"ASSET PLAYBOOK", "KẾ HOẠCH CHO TỪNG TÀI SẢN",
	"SCENARIO MATRIX", "CÁC KỊCH BẢN CẦN THEO DÕI",
	"DATA QUALITY", "ĐỘ TIN CẬY CỦA DỮ LIỆU",
	"confidence", "độ tin cậy",
	"Confidence", "Độ tin cậy",
	"invalidation", "mốc sai kịch bản",
	"Invalidation", "Mốc sai kịch bản",
	"exposure", "tỷ trọng vốn đang dùng",
	"Exposure", "Tỷ trọng vốn đang dùng",
	"probe", "thăm dò",
	"Probe", "Thăm dò",
	"scale", "tăng thêm",
	"Scale", "Tăng thêm",
	"liquidity", "thanh khoản",
	"Liquidity", "Thanh khoản",
	"allocation", "phân bổ vốn",
	"Allocation", "Phân bổ vốn",
	"fresh", "còn mới",
	"stale", "đã cũ",
	"STALE", "ĐÃ CŨ",
	"hard block", "lỗi buộc bot phải dừng",
	"gate", "điều kiện kiểm soát",
	"Gate", "Điều kiện kiểm soát",
	"Live readiness", "Kiểm tra sẵn sàng giao dịch thật",
	"live readiness", "kiểm tra sẵn sàng giao dịch thật",
	"Live proof", "Kiểm tra an toàn lệnh thật",
	"live proof", "kiểm tra an toàn lệnh thật",
	"Auto live order", "Lệnh thật tự động",
	"Manual live order", "Lệnh thật đặt tay",
	"Auto ladder", "Rải lệnh tự động",
	"Live supervisor", "Giám sát giao dịch thật",
	"live supervisor", "giám sát giao dịch thật",
	"Quản lý live orders", "Quản lý lệnh thật",
	"live orders", "lệnh thật",
	"live order", "lệnh thật",
	"Live positions", "Vị thế giao dịch thật",
	"live positions", "vị thế giao dịch thật",
	"live position", "vị thế giao dịch thật",
	"Reconcile live orders", "Đối soát lệnh thật",
	"Reconcile", "Đối soát",
	"reconcile", "đối soát",
	"Research Strategy Brief", "Tóm tắt tin tức chiến lược",
	"Research-only", "Tin tức chỉ để tham khảo",
	"Research", "Tin tức",
	"research", "tin tức",
	"Bot Alive", "Bot đang hoạt động",
	"Status", "Trạng thái",
	"status", "trạng thái",
	"Doctor", "Kiểm tra hệ thống",
	"doctor", "kiểm tra hệ thống",
	"PID", "Mã tiến trình",
	"Mode", "Chế độ",
	"mode", "chế độ",
	"DryRun", "Chạy thử",
	"dry-run", "chạy thử",
	"DRY-RUN", "CHẠY THỬ",
	"Auto live", "Tự động giao dịch thật",
	"auto live", "tự động giao dịch thật",
	"Auto execute", "Tự động đặt lệnh",
	"Manual confirm", "Xác nhận tay",
	"Proof only", "Chỉ kiểm tra an toàn",
	"proof", "kiểm tra an toàn",
	"Proof", "Kiểm tra an toàn",
	"Candidate", "Lệnh dự kiến",
	"candidate", "lệnh dự kiến",
	"notional", "giá trị",
	"Notional", "Giá trị",
	"Order engine", "Bộ quản lý lệnh",
	"Open orders", "Lệnh đang mở",
	"open orders", "lệnh đang mở",
	"Desired layers", "Tầng lệnh mong muốn",
	"desired", "mong muốn",
	"Desired", "Mong muốn",
	"Pending", "Vốn đang chờ",
	"State", "Trạng thái",
	"Action", "Hành động",
	"Trigger", "Điều kiện kích hoạt",
	"trigger", "điều kiện kích hoạt",
	"Watchlist", "Danh sách theo dõi",
	"watchlist", "danh sách theo dõi",
	"setup", "thế vào lệnh",
	"Setup", "Thế vào lệnh",
	"support", "hỗ trợ",
	"Support", "Hỗ trợ",
	"Regime", "Chế độ thị trường",
	"regime", "chế độ thị trường",
	"Trend score", "Điểm xu hướng",
	"trend score", "điểm xu hướng",
	"Trend", "Xu hướng",
	"trend", "xu hướng",
	"Bias", "Thiên hướng",
	"bias", "thiên hướng",
	"Flow", "Dòng tiền",
	"flow", "dòng tiền",
	"risk gate", "bộ kiểm soát rủi ro",
	"Risk gate", "Bộ kiểm soát rủi ro",
	"Risk governor", "Bộ kiểm soát rủi ro",
	"risk governor", "bộ kiểm soát rủi ro",
	"Risk", "Rủi ro",
	"risk", "rủi ro",
	"safety gate", "khóa an toàn",
	"Safety gate", "Khóa an toàn",
	"SAFETY", "AN TOÀN",
	"Safety", "An toàn",
	"safety", "an toàn",
	"blocker", "lý do chặn",
	"Blocker", "Lý do chặn",
	"blockers", "lý do chặn",
	"Blockers", "Lý do chặn",
	"Operator halt", "Khóa vận hành",
	"operator halt", "khóa vận hành",
	"OKX account", "Tài khoản OKX",
	"auth=", "xác thực=",
	"balance=", "số dư=",
	"USDT free", "USDT khả dụng",
	"Min", "Tối thiểu",
	"env", "biến môi trường",
	"market order", "lệnh thị trường",
	"Market order", "Lệnh thị trường",
	"futures", "hợp đồng tương lai",
	"Futures", "Hợp đồng tương lai",
	"leverage", "đòn bẩy",
	"Leverage", "Đòn bẩy",
	"spot limit BUY post-only", "mua giao ngay bằng lệnh giới hạn tạo thanh khoản",
	"Spot limit BUY post-only", "Mua giao ngay bằng lệnh giới hạn tạo thanh khoản",
	"spot limit", "lệnh giới hạn giao ngay",
	"Spot limit", "Lệnh giới hạn giao ngay",
	"post-only", "chỉ tạo thanh khoản",
	"limit", "giá giới hạn",
	"Limit", "Giá giới hạn",
	"layer", "tầng",
	"Layer", "Tầng",
	"ladder", "rải lệnh",
	"Ladder", "Rải lệnh",
	"cycle", "chu kỳ",
	"Cycle", "Chu kỳ",
	"filled", "đã khớp",
	"fill", "khớp lệnh",
	"avg", "giá trung bình",
	"client id", "mã phía bot",
	"order", "lệnh",
	"Order", "Lệnh",
	"Research đang tắt", "Thu thập tin tức đang tắt",
	"brief", "bản tóm tắt",
	"Brief", "Bản tóm tắt",
	"context", "bối cảnh",
	"override", "ghi đè",
	"news layer", "lớp tin tức",
	"catalyst", "chất xúc tác",
	"discount", "chiết khấu",
	"Discount", "Chiết khấu",
	"chase", "mua đuổi",
	"FOMO", "mua vội",
	"ACTIVE LIMIT", "ĐỦ ĐIỀU KIỆN ĐẶT LỆNH",
	"ACTIVE_LIMIT", "ĐỦ ĐIỀU KIỆN ĐẶT LỆNH",
	"ALLOWED", "ĐƯỢC PHÉP",
	"ARMED", "CHUẨN BỊ",
	"WATCH", "THEO DÕI",
	"NO_TRADE", "KHÔNG GIAO DỊCH",
	"DOWNTREND", "XU HƯỚNG GIẢM",
	"UPTREND", "XU HƯỚNG TĂNG",
	"RANGING", "ĐI NGANG",
	"LOW", "THẤP",
	"MEDIUM", "VỪA",
	"HIGH", "CAO",
)

// TelegramVietnamese normalizes user-facing Telegram text to Vietnamese terms.
// It intentionally leaves symbols, exchange names, IDs, status enums, and numbers intact when no safe Vietnamese phrase exists.
func TelegramVietnamese(s string) string {
	s = telegramVietnameseReplacer.Replace(s)
	// Fix composite words after enum normalization.
	s = strings.ReplaceAll(s, "THEO DÕILIST", "DANH SÁCH THEO DÕI")
	s = strings.ReplaceAll(s, "ĐƯỢC PHÉPLIST", "DANH SÁCH ĐƯỢC PHÉP")
	s = strings.ReplaceAll(s, "WEAK_XU HƯỚNG TĂNG/RANGE", "xu hướng tăng yếu/đi ngang")
	s = strings.ReplaceAll(s, "ACCUMULATION/WEAK_XU HƯỚNG TĂNG/RANGE", "tích lũy/xu hướng tăng yếu/đi ngang")
	s = strings.ReplaceAll(s, "bối cảnh only", "chỉ làm bối cảnh")
	s = strings.ReplaceAll(s, "probe=false", "thử lệnh=false")
	s = strings.ReplaceAll(s, "perm=", "quyền=")
	s = strings.ReplaceAll(s, "plan=", "kế hoạch=")
	s = strings.ReplaceAll(s, "Daily=", "Phân tích ngày=")
	s = strings.ReplaceAll(s, "Supervisor=", "Giám sát=")
	return s
}
